/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playersapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *PlayersGUI.java
 * 
 * Initially created 16/11/2017
 * 
 * Date last modified: 5/12/2017
 * 
 * @author Ting Hao Chang (x16370076), Joshua Cassidy (x16465134), Ciarán Brady (x16348791)
 * 
 * @reference for while loop https://stackoverflow.com/questions/39730789/continuous-loop-until-condition-is-met
 */
public class PlayersGUI extends javax.swing.JFrame {

    //Creates new instance of Players called p for storing data -Josh
    private Players p;
    //This ArrayList stores the information on each player that is entered in the GUI. - Ting
    private ArrayList<Players> play;
    //Creates an integer variable called j that is used to denote the index of the ArrayList players for use in the Next and Previous buttons -Josh
    private int j;

    /**
     * Creates new form PlayersGUI
     */
    public PlayersGUI() {
        initComponents();
        //This is initialising the ArrayList named play. - Ting
        play = new ArrayList<>();
        //This command is calling the readFromFile function, so that it pulls information previously saved to the players.dat file. -Ting
        readFromFile();
        //Sets p to be a new instance of Dota2 subclass -Josh
        p = new Dota2();
        //Sets j to be 0 when the project starts
        j = 0;
        
        //set visible code to show programs inital state before a game is selected - ciaran x16348791

        lblName.setVisible(false);
        fldName.setVisible(false);
        lblRegion.setVisible(false);
        fldRegion.setVisible(false);
        lblStatus.setVisible(false);
        fldStatus.setVisible(false);
        lblWinrate.setVisible(false);
        fldWinrate.setVisible(false);
        
        //This code sets the elements used for displaying Dota 2 data to be invisible on the program startup. - Ting
        lblD2Team.setVisible(false);
        lblD2Role.setVisible(false);
        lblD2Sponsor.setVisible(false);
        lblD2Main.setVisible(false);
        fldD2Team.setVisible(false);
        fldD2Role.setVisible(false);
        fldD2Sponsor.setVisible(false);
        fldD2Main.setVisible(false);

        lblTeamCS.setVisible(false);
        lblRoleCS.setVisible(false);
        lblSponsorCS.setVisible(false);
        fldTeamCS.setVisible(false);
        fldRoleCS.setVisible(false);
        fldSponsorCS.setVisible(false);

        //Sets Guilty Gear information in the GUI to be hidden on startup -Josh
        lblGGMain.setVisible(false);
        lblGGController.setVisible(false);
        lblGGSponsor.setVisible(false);
        fldGGMain.setVisible(false);
        fldGGController.setVisible(false);
        fldGGSponsor.setVisible(false);

        lblNameDisplay.setVisible(false);
        lblRegionDisplay.setVisible(false);
        lblStatusDisplay.setVisible(false);
        lblWinrateDisplay.setVisible(false);

        //Sets display labels for information on Guilty Gear players to be hidden on startup -Josh
        lblMainGGDisplay.setVisible(false);
        lblControllerGGDisplay.setVisible(false);
        lblSponsorGGDisplay.setVisible(false);
        
        //This also code sets the elements used for displaying Dota 2 data to be invisible on the program startup. - Ting
        lblTeamD2Display.setVisible(false);
        lblRoleD2Display.setVisible(false);
        lblMainD2Display.setVisible(false);
        lblSponsorD2Display.setVisible(false);

        lblTeamCSDisplay.setVisible(false);
        lblRoleCSDisplay.setVisible(false);
        lblSponsorCSDisplay.setVisible(false);

        //Sets buttons to be hidden on startup so they are not pushed when they should not be used, and so that the GUI is cleaner. -Josh
        btnEnter.setVisible(false);
        btnDisplay.setVisible(false);
        
        btnPrevious.setVisible(false);
        btnNext.setVisible(false);
        
        //This textfield is set to have the text inside it change based on the selected option in the combo box with instructional messages. - Ting
        //This code sets it so that it gives this message on startup. -Ting
        fldGuide.setText("Select the game you would like to enter/view player information for.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblWinrate = new javax.swing.JLabel();
        lblGGMain = new javax.swing.JLabel();
        lblGGController = new javax.swing.JLabel();
        lblGGSponsor = new javax.swing.JLabel();
        fldGGController = new javax.swing.JTextField();
        fldName = new javax.swing.JTextField();
        fldRegion = new javax.swing.JTextField();
        fldStatus = new javax.swing.JTextField();
        fldWinrate = new javax.swing.JTextField();
        fldGGMain = new javax.swing.JTextField();
        fldGGSponsor = new javax.swing.JTextField();
        cbGame = new javax.swing.JComboBox<>();
        lblD2Team = new javax.swing.JLabel();
        fldD2Team = new javax.swing.JTextField();
        lblD2Role = new javax.swing.JLabel();
        lblD2Sponsor = new javax.swing.JLabel();
        fldD2Role = new javax.swing.JTextField();
        fldD2Sponsor = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        lblTeamCS = new javax.swing.JLabel();
        fldTeamCS = new javax.swing.JTextField();
        fldRoleCS = new javax.swing.JTextField();
        fldSponsorCS = new javax.swing.JTextField();
        lblRoleCS = new javax.swing.JLabel();
        lblSponsorCS = new javax.swing.JLabel();
        lblD2Main = new javax.swing.JLabel();
        fldD2Main = new javax.swing.JTextField();
        fldGuide = new javax.swing.JTextField();
        lblNameDisplay = new javax.swing.JLabel();
        lblSponsorCSDisplay = new javax.swing.JLabel();
        lblRegionDisplay = new javax.swing.JLabel();
        lblStatusDisplay = new javax.swing.JLabel();
        lblWinrateDisplay = new javax.swing.JLabel();
        lblMainGGDisplay = new javax.swing.JLabel();
        lblControllerGGDisplay = new javax.swing.JLabel();
        lblSponsorGGDisplay = new javax.swing.JLabel();
        lblRoleD2Display = new javax.swing.JLabel();
        lblTeamD2Display = new javax.swing.JLabel();
        lblMainD2Display = new javax.swing.JLabel();
        lblSponsorD2Display = new javax.swing.JLabel();
        lblTeamCSDisplay = new javax.swing.JLabel();
        lblRoleCSDisplay = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setText("Player Details");

        lblName.setText("Name");

        lblRegion.setText("Region");

        lblStatus.setText("Status");

        lblWinrate.setText("Winrate");

        lblGGMain.setText("Main");

        lblGGController.setText("Controller");

        lblGGSponsor.setText("Sponsor");

        fldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldStatusActionPerformed(evt);
            }
        });

        fldGGMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldGGMainActionPerformed(evt);
            }
        });

        cbGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No game selected", "Dota 2", "Counter Strike: Global Offensive", "Guilty Gear Xrd" }));
        cbGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGameActionPerformed(evt);
            }
        });

        lblD2Team.setText("Team");

        lblD2Role.setText("Standard role");

        lblD2Sponsor.setText("Sponsor");

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        lblTeamCS.setText("Team");

        fldTeamCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldTeamCSActionPerformed(evt);
            }
        });

        fldSponsorCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSponsorCSActionPerformed(evt);
            }
        });

        lblRoleCS.setText("Role");

        lblSponsorCS.setText("Sponsor");

        lblD2Main.setText("Main");

        fldGuide.setEditable(false);
        fldGuide.setText("Please select the game you would like to enter/view player  information for.");
        fldGuide.setBorder(null);

        lblNameDisplay.setText("jLabel1");

        lblSponsorCSDisplay.setText("jLabel1");

        lblRegionDisplay.setText("jLabel1");

        lblStatusDisplay.setText("jLabel1");

        lblWinrateDisplay.setText("jLabel1");

        lblMainGGDisplay.setText("jLabel1");

        lblControllerGGDisplay.setText("jLabel1");

        lblSponsorGGDisplay.setText("jLabel1");

        lblRoleD2Display.setText("jLabel1");

        lblTeamD2Display.setText("jLabel1");

        lblMainD2Display.setText("jLabel1");

        lblSponsorD2Display.setText("jLabel1");

        lblTeamCSDisplay.setText("jLabel1");

        lblRoleCSDisplay.setText("jLabel1");

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(fldGuide, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTeamCS)
                                            .addComponent(lblD2Sponsor)
                                            .addComponent(lblD2Main)
                                            .addComponent(lblD2Role)
                                            .addComponent(lblD2Team)
                                            .addComponent(lblGGMain)
                                            .addComponent(lblRegion)
                                            .addComponent(lblName))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblGGController)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fldName, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(fldRegion)
                                    .addComponent(fldGGMain)
                                    .addComponent(fldD2Role)
                                    .addComponent(fldD2Main)
                                    .addComponent(fldD2Sponsor)
                                    .addComponent(fldTeamCS)
                                    .addComponent(fldRoleCS)
                                    .addComponent(fldSponsorCS)
                                    .addComponent(fldD2Team)
                                    .addComponent(fldGGSponsor)
                                    .addComponent(fldGGController)
                                    .addComponent(fldWinrate)
                                    .addComponent(fldStatus)))
                            .addComponent(lblRoleCS)
                            .addComponent(lblSponsorCS)
                            .addComponent(lblStatus)
                            .addComponent(lblWinrate)
                            .addComponent(lblGGSponsor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainGGDisplay)
                            .addComponent(lblNameDisplay)
                            .addComponent(lblSponsorCSDisplay)
                            .addComponent(lblRegionDisplay)
                            .addComponent(lblStatusDisplay)
                            .addComponent(lblControllerGGDisplay)
                            .addComponent(lblSponsorGGDisplay)
                            .addComponent(lblRoleD2Display)
                            .addComponent(lblTeamD2Display)
                            .addComponent(lblMainD2Display)
                            .addComponent(lblSponsorD2Display)
                            .addComponent(lblTeamCSDisplay)
                            .addComponent(lblRoleCSDisplay)
                            .addComponent(lblWinrateDisplay)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(cbGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fldGuide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(fldRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegionDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(fldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWinrate)
                    .addComponent(fldWinrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWinrateDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGGMain)
                    .addComponent(fldGGMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMainGGDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGGController)
                    .addComponent(fldGGController, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControllerGGDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGGSponsor)
                    .addComponent(fldGGSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSponsorGGDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD2Team)
                    .addComponent(fldD2Team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeamD2Display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD2Role)
                    .addComponent(fldD2Role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoleD2Display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD2Main)
                    .addComponent(fldD2Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMainD2Display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD2Sponsor)
                    .addComponent(fldD2Sponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSponsorD2Display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeamCS)
                    .addComponent(fldTeamCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeamCSDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoleCS)
                    .addComponent(fldRoleCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoleCSDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSponsorCS)
                    .addComponent(fldSponsorCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSponsorCSDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnter)
                    .addComponent(btnDisplay))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldStatusActionPerformed

    private void cbGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGameActionPerformed
        // TODO add your handling code here:
        //This set of if/else statements decided what is displayed when a game is selected within the combo box and sets where the data will be sent eg: if dota is select p becomes dota - ciaran x16348791
        if (cbGame.getSelectedItem().equals("Dota 2")) {
            //The following code sets labels/textfields/buttons to be visible or invisible based on the selected option in the combobox. -Ting
            lblName.setVisible(true);
            fldName.setVisible(true);
            lblRegion.setVisible(true);
            fldRegion.setVisible(true);
            lblStatus.setVisible(true);
            fldStatus.setVisible(true);
            lblWinrate.setVisible(true);
            fldWinrate.setVisible(true);

            lblD2Team.setVisible(true);
            lblD2Role.setVisible(true);
            lblD2Main.setVisible(true);
            lblD2Sponsor.setVisible(true);
            fldD2Team.setVisible(true);
            fldD2Role.setVisible(true);
            fldD2Main.setVisible(true);
            fldD2Sponsor.setVisible(true);

            lblTeamCS.setVisible(false);
            lblRoleCS.setVisible(false);
            lblSponsorCS.setVisible(false);
            fldTeamCS.setVisible(false);
            fldRoleCS.setVisible(false);
            fldSponsorCS.setVisible(false);

            lblGGMain.setVisible(false);
            lblGGController.setVisible(false);
            lblGGSponsor.setVisible(false);
            fldGGMain.setVisible(false);
            fldGGController.setVisible(false);
            fldGGSponsor.setVisible(false);

            btnEnter.setVisible(true);
            btnDisplay.setVisible(true);
            
            lblNameDisplay.setVisible(false);
            lblRegionDisplay.setVisible(false);
            lblStatusDisplay.setVisible(false);
            lblWinrateDisplay.setVisible(false);

            lblMainGGDisplay.setVisible(false);
            lblControllerGGDisplay.setVisible(false);
            lblSponsorGGDisplay.setVisible(false);

            lblTeamD2Display.setVisible(false);
            lblRoleD2Display.setVisible(false);
            lblMainD2Display.setVisible(false);
            lblSponsorD2Display.setVisible(false);

            lblTeamCSDisplay.setVisible(false);
            lblRoleCSDisplay.setVisible(false);
            lblSponsorCSDisplay.setVisible(false);
            
            btnPrevious.setVisible(false);
            btnNext.setVisible(false);

            //This code sets it so that it gives this message is displayed on the fldGuide label when Dota2 is selected on the combobox. -Ting
            fldGuide.setText("View or enter information on Dota 2 players.");

            //This sets p to be a new instance of Dota2 -Ting
            p = new Dota2();
            ////Sets j to be 0 when Dota 2 is selected on the combobox to avoid issues when trying to use the Next and Previous buttons when switching between games. -Josh
            j = 0;
        } else if (cbGame.getSelectedItem().equals("Counter Strike: Global Offensive")) {
            lblName.setVisible(true);
            fldName.setVisible(true);
            lblRegion.setVisible(true);
            fldRegion.setVisible(true);
            lblStatus.setVisible(true);
            fldStatus.setVisible(true);
            lblWinrate.setVisible(true);
            fldWinrate.setVisible(true);

            lblD2Team.setVisible(false);
            lblD2Role.setVisible(false);
            lblD2Main.setVisible(false);
            lblD2Sponsor.setVisible(false);
            fldD2Team.setVisible(false);
            fldD2Role.setVisible(false);
            fldD2Main.setVisible(false);
            fldD2Sponsor.setVisible(false);

            lblTeamCS.setVisible(true);
            lblRoleCS.setVisible(true);
            lblSponsorCS.setVisible(true);
            fldTeamCS.setVisible(true);
            fldRoleCS.setVisible(true);
            fldSponsorCS.setVisible(true);

            lblGGMain.setVisible(false);
            lblGGController.setVisible(false);
            lblGGSponsor.setVisible(false);
            fldGGMain.setVisible(false);
            fldGGController.setVisible(false);
            fldGGSponsor.setVisible(false);

            btnEnter.setVisible(true);
            btnDisplay.setVisible(true);
            
            lblNameDisplay.setVisible(false);
            lblRegionDisplay.setVisible(false);
            lblStatusDisplay.setVisible(false);
            lblWinrateDisplay.setVisible(false);

            lblMainGGDisplay.setVisible(false);
            lblControllerGGDisplay.setVisible(false);
            lblSponsorGGDisplay.setVisible(false);

            lblTeamD2Display.setVisible(false);
            lblRoleD2Display.setVisible(false);
            lblMainD2Display.setVisible(false);
            lblSponsorD2Display.setVisible(false);

            lblTeamCSDisplay.setVisible(false);
            lblRoleCSDisplay.setVisible(false);
            lblSponsorCSDisplay.setVisible(false);
            
            btnPrevious.setVisible(false);
            btnNext.setVisible(false);

            //This code sets it so that it gives this message is displayed on the fldGuide label when Counter Strike is selected on the combobox. -Ting
            fldGuide.setText("View or enter information on CS:GO players.");

            p = new CounterStrike();
            //Sets j to be 0 when Counter Strike: Global Offensive is selected on the combobox to avoid issues when trying to use the Next and Previous buttons when switching between games. -Josh
            j = 0;
        //Sets the following code to run if the selected option in the combo box is Guilty Gear Xrd -Josh
        } else if (cbGame.getSelectedItem().equals("Guilty Gear Xrd")) {
            //Sets the necessary labels, buttons, and text fields to be present for entering data or viewing data, and ensures anything else is hidden -Josh
            lblName.setVisible(true);
            fldName.setVisible(true);
            lblRegion.setVisible(true);
            fldRegion.setVisible(true);
            lblStatus.setVisible(true);
            fldStatus.setVisible(true);
            lblWinrate.setVisible(true);
            fldWinrate.setVisible(true);

            lblD2Team.setVisible(false);
            lblD2Role.setVisible(false);
            lblD2Sponsor.setVisible(false);
            lblD2Main.setVisible(false);
            fldD2Team.setVisible(false);
            fldD2Role.setVisible(false);
            fldD2Sponsor.setVisible(false);
            fldD2Main.setVisible(false);

            lblTeamCS.setVisible(false);
            lblRoleCS.setVisible(false);
            lblSponsorCS.setVisible(false);
            fldTeamCS.setVisible(false);
            fldRoleCS.setVisible(false);
            fldSponsorCS.setVisible(false);

            lblGGMain.setVisible(true);
            lblGGController.setVisible(true);
            lblGGSponsor.setVisible(true);
            fldGGMain.setVisible(true);
            fldGGController.setVisible(true);
            fldGGSponsor.setVisible(true);

            btnEnter.setVisible(true);
            btnDisplay.setVisible(true);
            
            lblNameDisplay.setVisible(false);
            lblRegionDisplay.setVisible(false);
            lblStatusDisplay.setVisible(false);
            lblWinrateDisplay.setVisible(false);

            lblMainGGDisplay.setVisible(false);
            lblControllerGGDisplay.setVisible(false);
            lblSponsorGGDisplay.setVisible(false);

            lblTeamD2Display.setVisible(false);
            lblRoleD2Display.setVisible(false);
            lblMainD2Display.setVisible(false);
            lblSponsorD2Display.setVisible(false);

            lblTeamCSDisplay.setVisible(false);
            lblRoleCSDisplay.setVisible(false);
            lblSponsorCSDisplay.setVisible(false);
            
            btnPrevious.setVisible(false);
            btnNext.setVisible(false);

            //This code sets it so that it gives this message is displayed on the fldGuide label when Guilty Gear Xrd is selected on the combobox. -Ting
            fldGuide.setText("View or enter information on Guilty Gear Xrd players.");

            //Sets p to be a new instance of the GuiltyGear class -Josh
            p = new GuiltyGear();
            //Sets j to be 0 when Guilty Gear Xrd is selected on the combobox to avoid issues when trying to use the Next and Previous buttons when switching between games. -Josh
            j = 0;
        //Sets the following code to execute if No game selected is the chosen option on the combo box -Josh
        } else {
            //Reverts the program to be how it was when it was initially loaded up
            lblName.setVisible(false);
            fldName.setVisible(false);
            lblRegion.setVisible(false);
            fldRegion.setVisible(false);
            lblStatus.setVisible(false);
            fldStatus.setVisible(false);
            lblWinrate.setVisible(false);
            fldWinrate.setVisible(false);

            lblD2Team.setVisible(false);
            lblD2Role.setVisible(false);
            lblD2Sponsor.setVisible(false);
            lblD2Main.setVisible(false);
            fldD2Team.setVisible(false);
            fldD2Role.setVisible(false);
            fldD2Sponsor.setVisible(false);
            fldD2Main.setVisible(false);

            lblTeamCS.setVisible(false);
            lblRoleCS.setVisible(false);
            lblSponsorCS.setVisible(false);
            fldTeamCS.setVisible(false);
            fldRoleCS.setVisible(false);
            fldSponsorCS.setVisible(false);

            lblGGMain.setVisible(false);
            lblGGController.setVisible(false);
            lblGGSponsor.setVisible(false);
            fldGGMain.setVisible(false);
            fldGGController.setVisible(false);
            fldGGSponsor.setVisible(false);

            btnEnter.setVisible(false);
            btnDisplay.setVisible(false);
            
            lblNameDisplay.setVisible(false);
            lblRegionDisplay.setVisible(false);
            lblStatusDisplay.setVisible(false);
            lblWinrateDisplay.setVisible(false);

            lblMainGGDisplay.setVisible(false);
            lblControllerGGDisplay.setVisible(false);
            lblSponsorGGDisplay.setVisible(false);

            lblTeamD2Display.setVisible(false);
            lblRoleD2Display.setVisible(false);
            lblMainD2Display.setVisible(false);
            lblSponsorD2Display.setVisible(false);

            lblTeamCSDisplay.setVisible(false);
            lblRoleCSDisplay.setVisible(false);
            lblSponsorCSDisplay.setVisible(false);
            
            btnPrevious.setVisible(false);
            btnNext.setVisible(false);

            //This code sets it so that it gives this message is displayed on the fldGuide label when Dota2 is selected on the combobox. -Ting
            fldGuide.setText("Select the game you would like to enter/view player information for.");
        }
    }//GEN-LAST:event_cbGameActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
       //This code sees if p is an instance of the Dota2, CounterStrike, or GuiltyGear subclass, and then executes the code within the if statement. -Ting
        if (p instanceof Dota2) {
            //This code takes the information from the textfields when Dota2 is selected on the combobox and puts them into p. 
            p.setName(fldName.getText());
            p.setRegion(fldRegion.getText());
            p.setStatus(fldStatus.getText());
            p.setWinrate(fldWinrate.getText());
            //The following code gets the text from textfields specific to the Dota 2 selection and puts them into p.
            ((Dota2) p).setTeam(fldD2Team.getText());
            ((Dota2) p).setRole(fldD2Role.getText());
            ((Dota2) p).setMain(fldD2Main.getText());
            ((Dota2) p).setSponsor(fldD2Sponsor.getText());
        } else if (p instanceof CounterStrike) {
            p.setName(fldName.getText());
            p.setRegion(fldRegion.getText());
            p.setStatus(fldStatus.getText());
            p.setWinrate(fldWinrate.getText());
            ((CounterStrike) p).setRoleCS(fldRoleCS.getText());
            ((CounterStrike) p).setTeamCS(fldTeamCS.getText());
            ((CounterStrike) p).setSponsorCS(fldSponsorCS.getText());
        //Checks if p is an instance of GuiltyGear class and executes following code if appropriate -Josh
        } else if (p instanceof GuiltyGear) {
            //Takes text from text fields and inserts them into p
            p.setName(fldName.getText());
            p.setRegion(fldRegion.getText());
            p.setStatus(fldStatus.getText());
            p.setWinrate(fldWinrate.getText());
            ((GuiltyGear) p).setMain(fldGGMain.getText());
            ((GuiltyGear) p).setController(fldGGController.getText());
            ((GuiltyGear) p).setSponsor(fldGGSponsor.getText());
        } else {
            //JOptionPane.showMessageDialog(null, "Please choose a game!");
        }
        //Takes the information that has just been added to p and inserts it as a record in the ArrayList play. -Josh
        play.add(p);
        //Calls the writeToFile function -Josh
        writeToFile();
    }//GEN-LAST:event_btnEnterActionPerformed

    //this code takes the first set of information for the selected game and displays it to the user when the display button is clicked -ciaran x16348791
    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        //This is a for loop -Ting
        for (Players i : play) {
            //This code checks if the current iteration of the loop is an instance of Dota2, and if the combobox has "Dota2" selected, and then executes the following code. -Ting
            if (i instanceof Dota2 && cbGame.getSelectedItem().equals("Dota 2")) {
                //This sets labels and textfields irrelevent to the displaying of data about Dota2 players to be invisible. It also hides the Enter and Display buttons. -Ting
                fldName.setVisible(false);
                fldRegion.setVisible(false);
                fldStatus.setVisible(false);
                fldWinrate.setVisible(false);
                fldGGMain.setVisible(false);
                fldGGController.setVisible(false);
                fldGGSponsor.setVisible(false);
                fldD2Team.setVisible(false);
                fldD2Role.setVisible(false);
                fldD2Main.setVisible(false);
                fldD2Sponsor.setVisible(false);
                fldTeamCS.setVisible(false);
                fldRoleCS.setVisible(false);
                fldSponsorCS.setVisible(false);

                lblNameDisplay.setVisible(true);
                lblRegionDisplay.setVisible(true);
                lblStatusDisplay.setVisible(true);
                lblWinrateDisplay.setVisible(true);

                lblMainGGDisplay.setVisible(false);
                lblControllerGGDisplay.setVisible(false);
                lblSponsorGGDisplay.setVisible(false);

                lblTeamD2Display.setVisible(true);
                lblRoleD2Display.setVisible(true);
                lblMainD2Display.setVisible(true);
                lblSponsorD2Display.setVisible(true);

                lblTeamCSDisplay.setVisible(false);
                lblRoleCSDisplay.setVisible(false);
                lblSponsorCSDisplay.setVisible(false);
                
                btnEnter.setVisible(false);
                btnDisplay.setVisible(false);
                
                btnPrevious.setVisible(true);
                btnNext.setVisible(true);

                //This code sets the display labels to show information about the player most recently entered into the Dota 2 section. -Ting
                lblNameDisplay.setText(i.getName());
                lblRegionDisplay.setText(i.getRegion());
                lblStatusDisplay.setText(i.getStatus());
                lblWinrateDisplay.setText(i.getWinrate());
                lblTeamD2Display.setText(((Dota2) (i)).getTeam());
                lblRoleD2Display.setText(((Dota2) (i)).getRole());
                lblSponsorD2Display.setText(((Dota2) (i)).getSponsor());
                lblMainD2Display.setText(((Dota2) (i)).getMain());

            } else if (i instanceof CounterStrike && cbGame.getSelectedItem().equals("Counter Strike: Global Offensive")) {
                fldName.setVisible(false);
                fldRegion.setVisible(false);
                fldStatus.setVisible(false);
                fldWinrate.setVisible(false);
                fldGGMain.setVisible(false);
                fldGGController.setVisible(false);
                fldGGSponsor.setVisible(false);
                fldD2Team.setVisible(false);
                fldD2Role.setVisible(false);
                fldD2Main.setVisible(false);
                fldD2Sponsor.setVisible(false);
                fldTeamCS.setVisible(false);
                fldRoleCS.setVisible(false);
                fldSponsorCS.setVisible(false);

                lblNameDisplay.setVisible(true);
                lblRegionDisplay.setVisible(true);
                lblStatusDisplay.setVisible(true);
                lblWinrateDisplay.setVisible(true);

                lblMainGGDisplay.setVisible(false);
                lblControllerGGDisplay.setVisible(false);
                lblSponsorGGDisplay.setVisible(false);

                lblTeamD2Display.setVisible(false);
                lblRoleD2Display.setVisible(false);
                lblMainD2Display.setVisible(false);
                lblSponsorD2Display.setVisible(false);

                lblTeamCSDisplay.setVisible(true);
                lblRoleCSDisplay.setVisible(true);
                lblSponsorCSDisplay.setVisible(true);
                
                btnEnter.setVisible(false);
                btnDisplay.setVisible(false);
                
                btnPrevious.setVisible(true);
                btnNext.setVisible(true);

                lblNameDisplay.setText(i.getName());
                lblRegionDisplay.setText(i.getRegion());
                lblStatusDisplay.setText(i.getStatus());
                lblWinrateDisplay.setText(i.getWinrate());
                lblTeamCSDisplay.setText(((CounterStrike) (i)).getTeamCS());
                lblRoleCSDisplay.setText(((CounterStrike) (i)).getRoleCS());
                lblSponsorCSDisplay.setText(((CounterStrike) (i)).getSponsorCS());
            //Checks if the index of player the loop is on is an instance of GuiltyGear, and if the selected option in the combobox is Guilty Gear Xrd -Josh
            } else if (i instanceof GuiltyGear && cbGame.getSelectedItem().equals("Guilty Gear Xrd")) {
                //Sets the following text fields to be hidden, and the display labels to be visible -Josh
                fldName.setVisible(false);
                fldRegion.setVisible(false);
                fldStatus.setVisible(false);
                fldWinrate.setVisible(false);
                fldGGMain.setVisible(false);
                fldGGController.setVisible(false);
                fldGGSponsor.setVisible(false);
                fldD2Team.setVisible(false);
                fldD2Role.setVisible(false);
                fldD2Main.setVisible(false);
                fldD2Sponsor.setVisible(false);
                fldTeamCS.setVisible(false);
                fldRoleCS.setVisible(false);
                fldSponsorCS.setVisible(false);

                lblNameDisplay.setVisible(true);
                lblRegionDisplay.setVisible(true);
                lblStatusDisplay.setVisible(true);
                lblWinrateDisplay.setVisible(true);

                lblMainGGDisplay.setVisible(true);
                lblControllerGGDisplay.setVisible(true);
                lblSponsorGGDisplay.setVisible(true);

                lblTeamD2Display.setVisible(false);
                lblRoleD2Display.setVisible(false);
                lblMainD2Display.setVisible(false);
                lblSponsorD2Display.setVisible(false);

                lblTeamCSDisplay.setVisible(false);
                lblRoleCSDisplay.setVisible(false);
                lblSponsorCSDisplay.setVisible(false);
                
                btnEnter.setVisible(false);
                btnDisplay.setVisible(false);
                
                btnPrevious.setVisible(true);
                btnNext.setVisible(true);

                //Sets text to be the most recent data entered of this class -Josh
                lblNameDisplay.setText(i.getName());
                lblRegionDisplay.setText(i.getRegion());
                lblStatusDisplay.setText(i.getStatus());
                lblWinrateDisplay.setText(i.getWinrate());
                lblMainGGDisplay.setText(((GuiltyGear) (i)).getMain());
                lblControllerGGDisplay.setText(((GuiltyGear) (i)).getController());
                lblSponsorGGDisplay.setText(((GuiltyGear) (i)).getSponsor());

            } else {
                //JOptionPane.showMessageDialog(null, "Please choose a game!");
            }
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void fldTeamCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldTeamCSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldTeamCSActionPerformed

    private void fldSponsorCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSponsorCSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSponsorCSActionPerformed

    private void fldGGMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldGGMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldGGMainActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        //Sets Next button to bring j down by one when Previous button is hit and Dota 2 is selected in the combo box, and j is less more than zero -Josh
        if (cbGame.getSelectedItem().equals("Dota 2") && j > 0){
            j--;
            //Loop that sets to keep going down if the index that the above j-- brings j to is an instance of CounterStrike or GuiltyGear, so that information on these do not display in the Dota section -Josh 
            while(play.get(j) instanceof CounterStrike || play.get(j) instanceof GuiltyGear){
                j--;
            }
          
            lblNameDisplay.setText(play.get(j).getName());
            lblRegionDisplay.setText(play.get(j).getRegion());
            lblStatusDisplay.setText(play.get(j).getStatus());
            lblWinrateDisplay.setText(play.get(j).getWinrate());
            lblTeamD2Display.setText(((Dota2)play.get(j)).getTeam());
            lblRoleD2Display.setText(((Dota2)play.get(j)).getRole());
            lblSponsorD2Display.setText(((Dota2)play.get(j)).getSponsor());
            lblMainD2Display.setText(((Dota2)play.get(j)).getMain());
        }
        else if(cbGame.getSelectedItem().equals("Counter Strike: Global Offensive") && j > 0){
            j--;
            while(play.get(j) instanceof Dota2 || play.get(j) instanceof GuiltyGear){
                j--;
            }
            lblNameDisplay.setText(play.get(j).getName());
            lblRegionDisplay.setText(play.get(j).getRegion());
            lblStatusDisplay.setText(play.get(j).getStatus());
            lblWinrateDisplay.setText(play.get(j).getWinrate());
            lblTeamCSDisplay.setText(((CounterStrike)play.get(j)).getTeamCS());
            lblRoleCSDisplay.setText(((CounterStrike)play.get(j)).getRoleCS());
            lblSponsorCSDisplay.setText(((CounterStrike)play.get(j)).getSponsorCS());
            
        }
        //This sets the Previous button code for the Guilty Gear section -Ting
        else if(cbGame.getSelectedItem().equals("Guilty Gear Xrd") && j > 0){
            j--;
            while(play.get(j) instanceof Dota2 || play.get(j) instanceof CounterStrike){
                j--;
            }
            lblNameDisplay.setText(play.get(j).getName());
            lblRegionDisplay.setText(play.get(j).getRegion());
            lblStatusDisplay.setText(play.get(j).getStatus());
            lblWinrateDisplay.setText(play.get(j).getWinrate());
            //The piece of code that says (GuiltyGear) grabs information specific to the GuiltyGear class -Ting
            lblMainGGDisplay.setText(((GuiltyGear)play.get(j)).getMain());
            lblControllerGGDisplay.setText(((GuiltyGear)play.get(j)).getController());
            lblSponsorGGDisplay.setText(((GuiltyGear)play.get(j)).getSponsor());
            
        }
        else{
            
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
            //System.out.println(j.getName());
//            Dota2 dota2 = new Dota2();
        //The -1 is there because the .size command gets the number of values in the array rather than the last value, so there would have been an error. -Ting
        if (cbGame.getSelectedItem().equals("Dota 2") && j < play.size()-1){
            j++;
            //Idea for while loop was taken from here https://stackoverflow.com/questions/39730789/continuous-loop-until-condition-is-met
            /*@reference https://stackoverflow.com/questions/39730789/continuous-loop-until-condition-is-met*/
            while(play.get(j) instanceof CounterStrike || play.get(j) instanceof GuiltyGear){
                j++;
            }
            lblNameDisplay.setText(play.get(j).getName());
            lblRegionDisplay.setText(play.get(j).getRegion());
            lblStatusDisplay.setText(play.get(j).getStatus());
            lblWinrateDisplay.setText(play.get(j).getWinrate());
            lblTeamD2Display.setText(((Dota2)play.get(j)).getTeam());
            lblRoleD2Display.setText(((Dota2)play.get(j)).getRole());
            lblSponsorD2Display.setText(((Dota2)play.get(j)).getSponsor());
            lblMainD2Display.setText(((Dota2)play.get(j)).getMain());
        }
        else if(cbGame.getSelectedItem().equals("Counter Strike: Global Offensive") && j < play.size()-1){
            j++;
            while(play.get(j) instanceof Dota2 || play.get(j) instanceof GuiltyGear){
                j++;
            }
            lblNameDisplay.setText(play.get(j).getName());
            lblRegionDisplay.setText(play.get(j).getRegion());
            lblStatusDisplay.setText(play.get(j).getStatus());
            lblWinrateDisplay.setText(play.get(j).getWinrate());
            lblTeamCSDisplay.setText(((CounterStrike)play.get(j)).getTeamCS());
            lblRoleCSDisplay.setText(((CounterStrike)play.get(j)).getRoleCS());
            lblSponsorCSDisplay.setText(((CounterStrike)play.get(j)).getSponsorCS());
            
        }
        //This sets the Next button code for the Guilty Gear section -Ting
        else if(cbGame.getSelectedItem().equals("Guilty Gear Xrd") && j < play.size()-1){
            j++;
            while(play.get(j) instanceof Dota2 || play.get(j) instanceof CounterStrike){
                j++;
            }
            lblNameDisplay.setText(play.get(j).getName());
            lblRegionDisplay.setText(play.get(j).getRegion());
            lblStatusDisplay.setText(play.get(j).getStatus());
            lblWinrateDisplay.setText(play.get(j).getWinrate());
            //The piece of code that says (GuiltyGear) grabs information specific to the GuiltyGear class -Ting
            lblMainGGDisplay.setText(((GuiltyGear)play.get(j)).getMain());
            lblControllerGGDisplay.setText(((GuiltyGear)play.get(j)).getController());
            lblSponsorGGDisplay.setText(((GuiltyGear)play.get(j)).getSponsor());
            
        }
        else{
            
        }
        
        
    }//GEN-LAST:event_btnNextActionPerformed

    public void writeToFile() {
        try {
            //Creates a file which information from the play ArrayList is written to -Josh
            File f = new File("players.dat");
            FileOutputStream fStream = new FileOutputStream(f);
            ObjectOutputStream oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(play);
            oStream.close();
        //Handles exceptions -Josh
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }
        

    public void readFromFile() {
        try {
            //Creates a file if it does not already exist which information is pulled from -Josh
            File f = new File("players.dat");
            FileInputStream fStream = new FileInputStream(f);
            ObjectInputStream oStream = new ObjectInputStream(fStream);

            play = (ArrayList<Players>) oStream.readObject();
            oStream.close();
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayersGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox<String> cbGame;
    private javax.swing.JTextField fldD2Main;
    private javax.swing.JTextField fldD2Role;
    private javax.swing.JTextField fldD2Sponsor;
    private javax.swing.JTextField fldD2Team;
    private javax.swing.JTextField fldGGController;
    private javax.swing.JTextField fldGGMain;
    private javax.swing.JTextField fldGGSponsor;
    private javax.swing.JTextField fldGuide;
    private javax.swing.JTextField fldName;
    private javax.swing.JTextField fldRegion;
    private javax.swing.JTextField fldRoleCS;
    private javax.swing.JTextField fldSponsorCS;
    private javax.swing.JTextField fldStatus;
    private javax.swing.JTextField fldTeamCS;
    private javax.swing.JTextField fldWinrate;
    private javax.swing.JLabel lblControllerGGDisplay;
    private javax.swing.JLabel lblD2Main;
    private javax.swing.JLabel lblD2Role;
    private javax.swing.JLabel lblD2Sponsor;
    private javax.swing.JLabel lblD2Team;
    private javax.swing.JLabel lblGGController;
    private javax.swing.JLabel lblGGMain;
    private javax.swing.JLabel lblGGSponsor;
    private javax.swing.JLabel lblMainD2Display;
    private javax.swing.JLabel lblMainGGDisplay;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameDisplay;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblRegionDisplay;
    private javax.swing.JLabel lblRoleCS;
    private javax.swing.JLabel lblRoleCSDisplay;
    private javax.swing.JLabel lblRoleD2Display;
    private javax.swing.JLabel lblSponsorCS;
    private javax.swing.JLabel lblSponsorCSDisplay;
    private javax.swing.JLabel lblSponsorD2Display;
    private javax.swing.JLabel lblSponsorGGDisplay;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusDisplay;
    private javax.swing.JLabel lblTeamCS;
    private javax.swing.JLabel lblTeamCSDisplay;
    private javax.swing.JLabel lblTeamD2Display;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWinrate;
    private javax.swing.JLabel lblWinrateDisplay;
    // End of variables declaration//GEN-END:variables
}
